### ISSUE TITLE
No completion for UFCS templates

### ISSUE THREAD

**Issue by AsafMah** [Pure-D/code-d#399] opened 2022-02-20 21:42 UTC
I'm using code-d on windows, and I tried to use the templates in alogirthms;
```d
import std.algorithm: map;
import std.digest.sha;

void main()
{
    auto arr = [1, 2, 3];
    auto arr2 = arr.map!(x => x * 2); // No completion for map! here
    auto arr3 = arr.map!(x => x * 2, 4 ,8); // No Error here until I hit "compile"
    auto arr4 = map!(x => x * 2)(arr); // Full completion, parameters info, etc
}
```

When using the `arr.map!` syntax, I don't get any completions or info about the method, but when doing map! I do

**Comment by WebFreak001** [comment] 2022-02-20 22:09
duplicate of #319

**Closed by WebFreak001** 2022-02-20 22:09 UTC
