### ISSUE TITLE
workspace-d and dcd-server should stop when closing vscode

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/code-d#3] opened 2015-12-09 03:01 UTC
With this plugin workspace-d and dcd-server start automatically when working with D files, however if you close vscode these processes remain behind. They should be closed when vscode closes IMHO. If I re-start vscode I get new workspace-d and dcd-server processes.

**Comment by WebFreak001** [comment] 2015-12-09 12:18
Thats a problem with vscode because I already added it to the dispose function but they never get called even though i register them. See https://github.com/WebFreak001/code-d/blob/master/src/extension.ts#L19 and https://github.com/WebFreak001/code-d/blob/master/src/workspace-d.ts#L196-L202

**Comment by gnunn1** [comment] 2015-12-28 02:15
I think this has been fixed in vscode 0.10.5 as workspace-d is no longer running after I exit vscode, can you confirm?

**Comment by WebFreak001** [comment] 2015-12-28 13:32
Confirmed fixed in vscode 0.10.6

**Closed by WebFreak001** 2015-12-28 13:32 UTC
Labels: bug, cantfix
