### ISSUE TITLE
macOS errors with DCD

### ISSUE THREAD

**Issue by joelcnz** [Pure-D/code-d#286] opened 2020-01-09 06:44 UTC
Get these errors coming up when I'm using it.

Says DCD is outdated, tries to update and finds there's already a zip file, after says it's installed successfully.

**Comment by WebFreak001** [comment] 2020-01-09 10:01
so does it work after it has unzipped the already existing zip file?

**Comment by joelcnz** [comment] 2020-01-17 08:55
<img width="462" alt="Screen Shot 2020-01-17 at 9 50 44 PM" src="https://user-images.githubusercontent.com/653293/72598130-0e78aa80-3974-11ea-8c18-235668ce233a.png">
I don't think it is working since it keeps saying it's outdated, and getting all this output and popups, (one popup says it couldn't initialize DCD. Another popup says d.dubPath is not a valid dub executable.

Here's a bit:

2020-01-17T20:12:10.216 [trace] async.d:79:setTimeout Setting timeout for 200 ms
2020-01-17T20:12:10.427 [trace] async.d:38:parallelMain Calling timeout
2020-01-17T20:12:10.461 [trace] app.d:79:processRequest Calling provideCodeLens
2020-01-17T20:12:10.564 [trace] app.d:79:processRequest Calling provideDocumentSymbols
2020-01-17T20:12:39.961 [trace] app.d:391:main GC run in 1 ms, 376 μs, and 3 hnsecs. Freed 2479136 bytes (7259408 bytes allocated, 29440752 bytes available)
2020-01-17T20:12:52.935 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:12:53.129 [trace] app.d:79:processRequest Calling provideCodeLens
2020-01-17T20:12:53.727 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:12:58.263 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:12:58.513 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:12:59.243 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:13:01.005 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:13:08.253 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:13:09.969 [trace] app.d:391:main GC run in 2 ms, 691 μs, and 8 hnsecs. Freed 23232 bytes (7337280 bytes allocated, 29362880 bytes available)
2020-01-17T20:13:23.817 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:13:25.232 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:13:39.985 [trace] app.d:391:main GC run in 2 ms, 522 μs, and 3 hnsecs. Freed 60800 bytes (7358416 bytes allocated, 29341744 bytes available)
2020-01-17T20:14:08.892 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:09.782 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:09.986 [trace] app.d:391:main GC run in 2 ms, 217 μs, and 3 hnsecs. Freed 36128 bytes (7376352 bytes allocated, 29323808 bytes available)
2020-01-17T20:14:10.289 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:10.705 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:11.066 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:11.451 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:11.677 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:14:39.988 [trace] app.d:391:main GC run in 1 ms, 778 μs, and 2 hnsecs. Freed 70848 bytes (7376416 bytes allocated, 29323744 bytes available)
2020-01-17T20:14:40.147 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:15:09.997 [trace] app.d:391:main GC run in 1 ms, 238 μs, and 4 hnsecs. Freed 34304 bytes (7390432 bytes allocated, 29309728 bytes available)
2020-01-17T20:15:40.010 [trace] app.d:391:main GC run in 2 ms, 448 μs, and 7 hnsecs. Freed 28880 bytes (7404624 bytes allocated, 29295536 bytes available)
2020-01-17T20:16:10.016 [trace] app.d:391:main GC run in 2 ms, 447 μs, and 9 hnsecs. Freed 43152 bytes (7404880 bytes allocated, 29295280 bytes available)
2020-01-17T20:16:40.027 [trace] app.d:391:main GC run in 3 ms, 319 μs, and 5 hnsecs. Freed 43616 bytes (7404624 bytes allocated, 29295536 bytes available)
2020-01-17T20:17:10.034 [trace] app.d:391:main GC run in 1 ms, 376 μs, and 5 hnsecs. Freed 43168 bytes (7404880 bytes allocated, 29295280 bytes available)
2020-01-17T20:17:27.083 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:17:27.095 [trace] app.d:79:processRequest Calling provideDocumentSymbols
2020-01-17T20:17:27.297 [trace] app.d:79:processRequest Calling provideCodeLens
2020-01-17T20:17:27.307 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:17:28.283 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:17:31.160 [trace] app.d:79:processRequest Calling provideHover
2020-01-17T20:17:31.621 [trace] app.d:79:processRequest Calling provideCodeActions
2020-01-17T20:17:32.252 [trace] async.d:79:setTimeout Setting timeout for 200 ms
2020-01-17T20:17:32.350 [trace] async.d:79:setTimeout Setting timeout for 200 ms
2020-01-17T20:17:32.554 [trace] async.d:38:parallelMain Calling timeout
std.regex.internal.ir.RegexException@/Users/runner/hostedtoolcache/dc/ldc2-1.18.0/x64/ldc2-1.18.0-osx-x86_64/bin/../import/std/regex/internal/parser.d(1018): non-monotonic prefix function(s), an unsorted range or duplicate key->value mapping
Pattern with error: `[\p{Alphabetic}_][\w_]*` <--HERE-- ``
----------------
??:? pure @safe void core.internal.utf.validate!(immutable(dchar)[]).validate(scope const(immutable(dchar)[])) [0x1062d6a7e]
??:? pure nothrow @nogc @safe uint rt.cover.max!(uint).max(uint, uint) [0x1062f632a]
??:? pure nothrow @nogc @safe uint rt.cover.max!(uint).max(uint, uint) [0x1062f6ffe]
??:? ref @trusted std.regex.internal.parser.Parser!(immutable(char)[], std.regex.internal.parser.CodeGen).Parser std.regex.internal.parser.Parser!(immutable(char)[], std.regex.internal.parser.CodeGen).Parser.__ctor!(const(char)[]).__ctor(immutable(char)[], const(char)[]) [0x105d42ba0]
??:? std.regex.internal.ir.Regex!(char).Regex std.functional.memoize!(std.regex.regexImpl!(immutable(char)[]).regexImpl(immutable(char)[], const(char)[]), 8).memoize(immutable(char)[], const(char)[]) [0x105d427e3]
??:? @trusted std.regex.internal.ir.Regex!(char).Regex std.regex.regex!(immutable(char)[]).regex(immutable(char)[][], const(char)[]) [0x105d4240b]
??:? @trusted std.regex.internal.ir.Regex!(char).Regex std.regex.regex!(immutable(char)[]).regex(immutable(char)[], const(char)[]) [0x1062692e5]
??:? bool std.algorithm.iteration.FilterResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda3, std.algorithm.iteration.MapResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda2, const(dparse.ast.Attribute)[]).MapResult).FilterResult.__xopEquals(ref const(std.algorithm.iteration.FilterResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda3, std.algorithm.iteration.MapResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda2, const(dparse.ast.Attribute)[]).MapResult).FilterResult), ref const(std.algorithm.iteration.FilterResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda3, std.algorithm.iteration.MapResult!(dscanner.analysis.unmodified.UnmodifiedFinder.canFindImmutableOrConst(const(dparse.ast.Declaration)).__lambda2, const(dparse.ast.Attribute)[]).MapResult).FilterResult)) [0x105f1de66]
??:? pure nothrow @nogc @safe bool std.functional.not!(dscanner.analysis.redundant_storage_class.RedundantStorageClassCheck.checkVariableDeclaration(const(dparse.ast.VariableDeclaration), const(dparse.ast.Attribute[])).__lambda4).not!(immutable(char)[]).not(ref immutable(char)[]) [0x105ee702b]
??:? workspaced.api.Future!(std.json.JSONValue).Future workspaced.com.dscanner.DscannerComponent.__mixin6.runMethod!("listAllIniFields").runMethod(std.json.JSONValue[]) [0x105e209dd]
??:? pure nothrow @nogc @safe const(ulong) std.math.powIntegralImpl!(0, const(ulong)).powIntegralImpl(const(ulong)) [0x10624dcb0]
??:? pure nothrow @nogc void std.parallelism.atomicSetUbyte!(ubyte).atomicSetUbyte(ref ubyte, ubyte) [0x10624de5a]
??:? _DThn16_4core4sync5mutex5Mutex6unlockMFNeZv [0x1062d8484]
??:? _pthread_start [0x7fff697a1d75]

**Comment by WebFreak001** [comment] 2020-01-17 14:56
see https://github.com/dlang-community/DCD/issues/610

**Comment by bitjson** [comment] 2020-02-01 20:41
In my case, there were two issues. 

Following the discussion in https://github.com/dlang-community/DCD/issues/610, I rebuilt from source:

```
brew reinstall dcd --build-from-source
```

After which I could confirm that my local `dcd-server` and `dcd-client` were no longer crashing.

When reloading VSCode though, this extension didn't seem to be able to find them and kept trying to install crashing versions at `~/.code-d/bin/`.

I ran `which dcd-client && which dcd-server`, and I symlinked the results in that directory:
```
ln -s /usr/local/bin/dcd-client ~/.code-d/bin/dcd-client
ln -s /usr/local/bin/dcd-server ~/.code-d/bin/dcd-server
```

And now things are working properly. 👍

**Comment by ArnaudValensi** [comment] 2020-04-24 17:17
The dcd-server and dcd-client automatically installed do not work on MacOs Catalina.
Doing what @bitjson said works well.

**Comment by joelcnz** [comment] 2020-08-30 06:31
I tried @bitjson post, but no different, though I'm not totally sure I did it right.

**Comment by WebFreak001** [comment] 2022-01-20 20:23
probably duplicate of #312 

should be fixed in latest serve-d/code-d version

**Closed by WebFreak001** 2022-01-20 20:23 UTC
