### ISSUE TITLE
Can't see autocompletion box

### ISSUE THREAD

**Issue by bojan-misic** [Pure-D/code-d#32] opened 2016-03-01 00:09 UTC
I'm using OS X 10.11.3, installed *DCD*, *Dscanner*, *Dfmt* and *Workspace-D*, all in $PATH. 

I've created a **vibe.d** project template and loaded to VSCode, and for the first couple of seconds I do see autocomplete for already defined variables and function parameters, but as soon as I press **"."** to access object's fields and methods, I no longer see that autocomplete popup until I restart VSCode. Sometimes it breaks immediately even on the fresh start, sometimes after I press **"."** for the first time. It also doesn't work with the import statements. Not sure what I am missing.

By looking at Developer Tool's console, everything looks fine - I see object I'm supposed to get:

```
[Plugin Host] WorkspaceD Debug: Server: 2016-03-01T01:03:10.851:server.d:main:245 Request processed in 1.51742 milliseconds

workbench.main.js:88 [Plugin Host] resolve
workbench.main.js:88 [Plugin Host] Array[7]0: Object1: Object2: Object3: Object4: Object5: Object6: Objectlength: 7__proto__: Array[0]
```

Sorry if this has been resolved before, I couldn't find it.
Thanks in advance.

**Comment by WebFreak001** [comment] 2016-03-01 12:10
known issue on OS X. I have no idea why it happens because vscode receives the data from the plugin. Help would be nice as I dont have OS X or a way to emulate it

Duplicate of https://github.com/Pure-D/code-d/issues/29

**Closed by WebFreak001** 2016-03-01 12:10 UTC
