### ISSUE TITLE
Might be me ...

### ISSUE THREAD

**Issue by sjk7** [Pure-D/code-d#129] opened 2017-06-29 21:36 UTC
Hello!
Thanks for all the hard work. Nice plugin.

My issue is that i would like autocomplete to pop up suggestions when I hit a period, rather than as it is for me now, which is you have to type a letter after the period. Pressing CTRL+SPACE does work when I am at the period, but I'd rather it was automatically doing this. Is there some config I can set for this?
Thanks!

**Comment by WebFreak001** [comment] 2017-06-29 23:35
it should do that already, it might be that you have too many symbols and dcd can't show them all without providing at least one character? But that doesn't make sense if ctrl+space works. Um I'm planning on releasing the new rewrite soon (ETA unknown), maybe it will fix itself then

**Comment by Wulfklaue** [comment] 2017-07-06 16:11
The issue is that pressing a period does not work correctly. Using ctrl+space simply loads up all the symbols in the scope. Most that have nothing to do with the class / ... that your manipulating.

I just tried out the other plugin dlang-vscode and that seems to also have the same issues. Strange ... 

And its slow ... when i compare to c#, the whole d plugins are so slow...  That is not a code-d issue.

I like D as a language but its for everybody including WebFreak a frustration to constantly deal with all the lose plugins that keep breaking. In the last 6 months i have seen half a dozen times where things break because: plug vs install dmd ( latest ), changes in the plugins, etc ... i said it before, good / great language but so much frustration around it.

**Comment by RUSshy** [comment] 2017-07-31 17:54
this is why i stopped using d, it feels not mature, even tooling is 0, i'm waiting for serve-d to come in hope it gives good ide features, but even that is too much to ask for D, sadly :( i wish top level of comunity would care about this, because this is reason my team dont want touch D and stick to C# and C++ even if i tell them how good language is

**Comment by dhasenan** [comment] 2017-08-02 23:26
I'm getting the same problem. When I compiled a debug build from workspace-d HEAD (25319ea2ad58282d67a6dde8b5f374d06e19369c) or tag v2.11.0, the error message in the console went away, but I still didn't get completion. I tried wrapping this in a script that would log when it was started and what it emitted on stdout, but nothing was logged; the script was never invoked.

**Comment by WebFreak001** [comment] 2018-04-03 22:39
should all be fixed now for basically all cases

**Closed by WebFreak001** 2018-04-03 22:39 UTC
