### ISSUE TITLE
code-d not working in multiproject workspaces

### ISSUE THREAD

**Issue by Extrawurst** [Pure-D/code-d#151] opened 2017-12-27 17:03 UTC
if I open the project alone in a vscode instance everything works, if I use a workspace with this 
folder contained it does not:

![image](https://user-images.githubusercontent.com/776816/34387694-03e96396-eb30-11e7-80dd-d8eab0e2c6c6.png)

console:
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] rejected promise not handled within 1 second
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10 [webfreak.code-d-beta] Dub isn't initialized yet: Error: Dub isn't initialized yet
	at new ResponseError (/Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:421:48)
	at processMessageQueue (/Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:249:17)
	at Immediate.<anonymous> (/Users/stephan/.vscode/extensions/webfreak.code-d-beta-0.17.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:233:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
e.onUnexpectedError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:10
3/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] rejected promise not handled within 1 second
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:9
```

![image](https://user-images.githubusercontent.com/776816/34387716-16c2fe14-eb30-11e7-9f8b-2ab4722592ff.png)

**Comment by WebFreak001** [comment] 2017-12-27 17:05
with code-d beta the console doesn't contain any useful information anymore. Send the output from the output window (code-d/serve-d beta)

**Comment by WebFreak001** [comment] 2017-12-27 17:06
probably duplicate of #111 though

**Comment by Extrawurst** [comment] 2017-12-27 17:15
```
2017-12-27T18:08:21.337:app.d:main:201 Features fulfilled
2017-12-27T18:08:21.338:app.d:main:205 Started reading from stdin
2017-12-27T18:08:21.338:app.d:main:209 RPC started
2017-12-27T18:08:21.351:app.d:main:220 Has Message
2017-12-27T18:08:21.351:app.d:main:222 Message: RequestMessage(0, "initialize", {"capabilities":{"textDocument":{"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"hover":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true}},"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"workspaceEdit":{"documentChanges":true}}},"processId":93560,"rootPath":"\/Users\/stephan\/code\/liveask\/frontend","rootUri":"file:\/\/\/Users\/stephan\/code\/liveask\/frontend","trace":"off"})
2017-12-27T18:08:21.363:app.d:__lambda10:228 Processing as request
2017-12-27T18:08:21.363:app.d:processRequest:50 Initializing
2017-12-27T18:08:21.364:extension.d:initialize:139 Initializing serve-d for /Users/stephan/code/liveask/frontend
2017-12-27T18:08:21.364:extension.d:initialize:152 Starting dub...
2017-12-27T18:08:21.529:extension.d:safe:48 object.Exception@../../../../../.dub/packages/dub-1.4.1/dub/source/dub/dependency.d(657): Invalid SemVer format: ^2.4.1
----------------
4   serve-d                             0x0000000109fc56d5 pure @safe bool std.exception.enforce!(Exception, bool).enforce(bool, lazy const(char)[], immutable(char)[], ulong) + 149
5   serve-d                             0x000000010a07ef2c ref @safe dub.dependency.Version dub.dependency.Version.__ctor(immutable(char)[]) + 188
6   serve-d                             0x000000010a07bfb4 @property @trusted void dub.dependency.Dependency.versionSpec(immutable(char)[]) + 580
7   serve-d                             0x000000010a07d798 @trusted dub.dependency.Dependency dub.dependency.Dependency.fromJson(dub.internal.vibecompat.data.json.Json) + 1784
8   serve-d                             0x000000010a0f6d9d dub.dependency.Dependency dub.internal.vibecompat.data.json.deserializeJson!(dub.dependency.Dependency).deserializeJson(dub.internal.vibecompat.data.json.Json) + 129
9   serve-d                             0x000000010a146ba1 int dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.BuildSettingsTemplate, dub.internal.vibecompat.data.json.Json, immutable(char)[]).__foreachbody4(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json).__foreachbody3(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json) + 345
10  serve-d                             0x000000010a0ee804 int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)).__foreachbody2(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json) + 72
11  serve-d                             0x000000010a173828 _aaApply2 + 136
12  serve-d                             0x000000010a0ee793 int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)) + 87
13  serve-d                             0x000000010a145f2c int dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.BuildSettingsTemplate, dub.internal.vibecompat.data.json.Json, immutable(char)[]).__foreachbody4(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json) + 284
14  serve-d                             0x000000010a0ee804 int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)).__foreachbody2(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json) + 72
15  serve-d                             0x000000010a173828 _aaApply2 + 136
16  serve-d                             0x000000010a0ee793 int dub.internal.vibecompat.data.json.Json.opApply(int delegate(ref immutable(char)[], ref dub.internal.vibecompat.data.json.Json)) + 87
17  serve-d                             0x000000010a145e06 void dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.BuildSettingsTemplate, dub.internal.vibecompat.data.json.Json, immutable(char)[]) + 38
18  serve-d                             0x000000010a144c8a void dub.recipe.json.parseJson(ref dub.recipe.packagerecipe.PackageRecipe, dub.internal.vibecompat.data.json.Json, immutable(char)[]) + 258
19  serve-d                             0x000000010a1445eb dub.recipe.packagerecipe.PackageRecipe dub.recipe.io.readPackageRecipe(dub.internal.vibecompat.inet.path.Path, immutable(char)[]) + 1027
20  serve-d                             0x000000010a10a214 dub.package_.Package dub.package_.Package.load(dub.internal.vibecompat.inet.path.Path, dub.internal.vibecompat.inet.path.Path, dub.package_.Package, immutable(char)[]) + 192
21  serve-d                             0x000000010a10f7a8 dub.package_.Package dub.packagemanager.PackageManager.getOrLoadPackage(dub.internal.vibecompat.inet.path.Path, dub.internal.vibecompat.inet.path.Path, bool) + 124
22  serve-d                             0x0000000109ea44cc void workspaced.com.dub.startup(immutable(char)[], bool, bool, bool) + 676
23  serve-d                             0x0000000109dd55e8 bool served.extension.safe!(workspaced.com.dub.startup(immutable(char)[], bool, bool, bool), immutable(char)[]).safe(immutable(char)[]) + 44
24  serve-d                             0x0000000109dc4fae served.protocol.InitializeResult served.extension.initialize(served.protocol.InitializeParams) + 570
25  serve-d                             0x0000000109d6cd61 served.protocol.ResponseMessage app.processRequest(served.protocol.RequestMessage) + 269
26  serve-d                             0x0000000109d725bf void app.main(immutable(char)[][]).__lambda10() + 99
27  serve-d                             0x000000010a16455b void core.thread.Fiber.run() + 43
28  serve-d                             0x000000010a163d96 fiber_entryPoint + 98
29  ???                                 0xffffffffffffffff 0x0 + 18446744073709551615
2017-12-27T18:08:21.534:extension.d:initialize:159 Failed starting dub - falling back to fsworkspace
2017-12-27T18:08:21.535:jsonrpc.d:showErrorMessage:310 Error message:  Could not initialize dub. Falling back to limited functionality!
2017-12-27T18:08:21.535:jsonrpc.d:send:66 {"jsonrpc":"2.0","method":"window/showMessage","params":{"message":" Could not initialize dub. Falling back to limited functionality!","type":1}}
2017-12-27T18:08:21.535:extension.d:initialize:189 Starting dscanner
2017-12-27T18:08:21.535:extension.d:initialize:192 Starting dfmt
2017-12-27T18:08:21.535:extension.d:initialize:194 Starting dlangui
2017-12-27T18:08:21.535:extension.d:initialize:196 Starting importer
2017-12-27T18:08:21.535:extension.d:initialize:198 Starting moduleman
2017-12-27T18:08:21.535:app.d:processRequest:52 Initialized
2017-12-27T18:08:21.535:app.d:__lambda10:230 Responding with: ResponseMessage(0, {"capabilities":{"codeActionProvider":true,"codeLensProvider":null,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","(","[","="]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":false,"documentLinkProvider":null,"documentOnTypeFormattingProvider":null,"documentRangeFormattingProvider":false,"documentSymbolProvider":true,"executeCommandProvider":null,"experimental":null,"hoverProvider":true,"referencesProvider":false,"renameProvider":false,"signatureHelpProvider":{"triggerCharacters":["(","[",","]},"textDocumentSync":2,"workspaceSymbolProvider":true}}, null(ResponseError))
2017-12-27T18:08:21.535:jsonrpc.d:send:66 {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":null,"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","(","[","="]},"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":false,"documentLinkProvider":null,"documentOnTypeFormattingProvider":null,"documentRangeFormattingProvider":false,"documentSymbolProvider":true,"executeCommandProvider":null,"experimental":null,"hoverProvider":true,"referencesProvider":false,"renameProvider":false,"signatureHelpProvider":{"triggerCharacters":["(","[",","]},"textDocumentSync":2,"workspaceSymbolProvider":true}}}
2017-12-27T18:08:21.546:app.d:main:220 Has Message
2017-12-27T18:08:21.546:app.d:main:222 Message: RequestMessage(none, "initialized", {})
2017-12-27T18:08:21.558:app.d:__lambda11:244 Processing as notification
2017-12-27T18:08:21.558:app.d:main:220 Has Message
2017-12-27T18:08:21.558:app.d:main:222 Message: RequestMessage(none, "$/setTraceNotification", {"value":"off"})
2017-12-27T18:08:21.568:app.d:__lambda11:244 Processing as notification
2017-12-27T18:08:21.568:app.d:main:220 Has Message
2017-12-27T18:08:21.568:app.d:main:222 Message: RequestMessage(none, "workspace/didChangeConfiguration", {"settings":{"d":{"aggressiveUpdate":true,"dcdClientPath":"\/Users\/stephan\/.code-d\/bin\/DCD\/dcd-client","dcdServerPath":"\/Users\/stephan\/.code-d\/bin\/DCD\/dcd-server","dfmtPath":"\/Users\/stephan\/.vscode\/extensions\/webfreak.code-d-0.16.2\/bin\/dfmt\/bin\/dfmt","dscannerPath":"\/Users\/stephan\/.vscode\/extensions\/webfreak.code-d-0.16.2\/bin\/Dscanner\/bin\/dscanner","dubArchType":"","dubBuildType":"","dubCompiler":"","dubConfiguration":"","dubPath":"\/usr\/local\/bin\/dub","enableAutoComplete":true,"enableDubLinting":true,"enableFormatting":true,"enableLinting":true,"enableSDLLinting":true,"enableStaticLinting":true,"neverUseDub":false,"overrideDfmtEditorconfig":true,"projectImportPaths":[],"servedPath":"\/Users\/stephan\/.vscode\/extensions\/webfreak.code-d-beta-0.17.4\/bin\/serve-d\/serve-d","stdlibPath":["\/Library\/D\/dmd\/src\/druntime\/import","\/Library\/D\/dmd\/src\/phobos"],"workspacedPath":"\/Users\/stephan\/.vscode\/extensions\/webfreak.code-d-0.16.2\/bin\/workspace-d\/workspace-d"},"dfmt":{"alignSwitchStatements":true,"braceStyle":"allman","compactLabeledStatements":true,"outdentAttributes":true,"selectiveImportSpace":true,"spaceAfterCast":true,"splitOperatorAtLineEnd":false,"templateConstraintStyle":"conditional_newline_indent"},"editor":{"acceptSuggestionOnCommitCharacter":true,"acceptSuggestionOnEnter":"on","accessibilitySupport":"auto","autoClosingBrackets":true,"autoIndent":true,"codeLens":true,"colorDecorators":true,"cursorBlinking":"blink","cursorStyle":"line","detectIndentation":true,"dragAndDrop":true,"emptySelectionClipboard":true,"find":{"autoFindInSelection":false,"seedSearchStringFromSelection":true},"folding":true,"fontFamily":"Menlo, Monaco, 'Courier New', monospace","fontLigatures":false,"fontSize":14,"fontWeight":"normal","formatOnPaste":false,"formatOnSave":true,"formatOnType":false,"glyphMargin":true,"hideCursorInOverviewRuler":false,"insertSpaces":true,"letterSpacing":0,"lightbulb":{"enabled":true},"lineHeight":0,"lineNumbers":"on","links":true,"matchBrackets":true,"minimap":{"enabled":true,"maxColumn":120,"renderCharacters":true,"showSlider":"mouseover"},"mouseWheelScrollSensitivity":1,"mouseWheelZoom":false,"multiCursorModifier":"alt","occurrencesHighlight":true,"overviewRulerBorder":true,"overviewRulerLanes":3,"parameterHints":true,"quickSuggestions":{"comments":false,"other":true,"strings":false},"quickSuggestionsDelay":10,"renderControlCharacters":false,"renderIndentGuides":true,"renderLineHighlight":"line","renderWhitespace":"all","roundedSelection":true,"rulers":[],"scrollBeyondLastLine":true,"selectionHighlight":true,"showFoldingControls":"mouseover","smoothScrolling":false,"snippetSuggestions":"inline","stablePeek":false,"suggestFontSize":0,"suggestLineHeight":0,"suggestOnTriggerCharacters":true,"tabCompletion":false,"tabSize":4,"tokenColorCustomizations":{},"trimAutoWhitespace":true,"useTabStops":true,"wordBasedSuggestions":true,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>\/?","wordWrap":"on","wordWrapColumn":80,"wrappingIndent":"same"},"git":{"autofetch":true,"autorefresh":true,"checkoutType":"all","confirmSync":true,"countBadge":"all","decorations":{"enabled":true},"defaultCloneDirectory":null,"enableCommitSigning":false,"enableSmartCommit":false,"enabled":true,"ignoreLegacyWarning":false,"ignoreLimitWarning":false,"path":null}}})
2017-12-27T18:08:21.579:app.d:__lambda11:244 Processing as notification
2017-12-27T18:08:21.579:extension.d:configNotify:213 Received configuration
Server: 2017-12-27T18:08:21.696:main.d:main:122 Starting up...

Server: 2017-12-27T18:08:21.697:main.d:main:156 Listening at /var/folders/vs/14nrtk3j2fs2lxw014_11qv80000gn/T/workspace-d-sock207D

Server: 2017-12-27T18:08:23.105:first.d:visit:411 Could not resolve location of module 'gcc/builtins'

Server: 2017-12-27T18:08:25.469:first.d:visit:411 Could not resolve location of module 'ldc/intrinsics'

Server: 2017-12-27T18:08:26.928:main.d:main:173 Import directories:

Server:     /Library/D/dmd/src/druntime/import

Server:     /Library/D/dmd/src/phobos

Server: 2017-12-27T18:08:26.928:main.d:main:179 105620 symbols cached.

Server: 2017-12-27T18:08:26.928:main.d:main:180 Startup completed in 5231.31 milliseconds.

2017-12-27T18:08:26.954:extension.d:startDCD:259 Imports: ["/Users/stephan/code/liveask/frontend", "/Users/stephan/code/liveask/frontend/src"]
2017-12-27T18:08:26.968:app.d:main:220 Has Message
2017-12-27T18:08:26.968:app.d:main:222 Message: RequestMessage(1, "served/getConfig", null)
2017-12-27T18:08:26.981:app.d:__lambda10:228 Processing as request
2017-12-27T18:08:26.981:app.d:processRequest:77 Calling getConfig
2017-12-27T18:08:26.981:app.d:__lambda10:230 Responding with: ResponseMessage(1, null, const(ResponseError)(serverNotInitialized, "Dub isn't initialized yet", null))
{"code":-32002,"data":null,"message":"Dub isn't initialized yet"}
2017-12-27T18:08:26.981:jsonrpc.d:send:66 {"error":{"code":-32002,"data":null,"message":"Dub isn't initialized yet"},"id":1,"jsonrpc":"2.0"}
2017-12-27T18:08:26.981:app.d:main:220 Has Message
2017-12-27T18:08:26.981:app.d:main:222 Message: RequestMessage(2, "served/getArchType", null)
2017-12-27T18:08:26.993:app.d:__lambda10:228 Processing as request
2017-12-27T18:08:26.993:app.d:processRequest:77 Calling getArchType
2017-12-27T18:08:26.993:app.d:__lambda10:230 Responding with: ResponseMessage(2, null, const(ResponseError)(serverNotInitialized, "Dub isn't initialized yet", null))
{"code":-32002,"data":null,"message":"Dub isn't initialized yet"}
2017-12-27T18:08:26.993:jsonrpc.d:send:66 {"error":{"code":-32002,"data":null,"message":"Dub isn't initialized yet"},"id":2,"jsonrpc":"2.0"}
2017-12-27T18:08:26.994:app.d:main:220 Has Message
2017-12-27T18:08:26.994:app.d:main:222 Message: RequestMessage(3, "served/getBuildType", null)
2017-12-27T18:08:27.005:app.d:__lambda10:228 Processing as request
2017-12-27T18:08:27.005:app.d:processRequest:77 Calling getBuildType
2017-12-27T18:08:27.006:app.d:__lambda10:230 Responding with: ResponseMessage(3, null, const(ResponseError)(serverNotInitialized, "Dub isn't initialized yet", null))
{"code":-32002,"data":null,"message":"Dub isn't initialized yet"}
2017-12-27T18:08:27.006:jsonrpc.d:send:66 {"error":{"code":-32002,"data":null,"message":"Dub isn't initialized yet"},"id":3,"jsonrpc":"2.0"}
2017-12-27T18:08:27.006:app.d:main:220 Has Message
2017-12-27T18:08:27.006:app.d:main:222 Message: RequestMessage(4, "served/getCompiler", null)
2017-12-27T18:08:27.016:app.d:__lambda10:228 Processing as request
2017-12-27T18:08:27.016:app.d:processRequest:77 Calling getCompiler
2017-12-27T18:08:27.016:app.d:__lambda10:230 Responding with: ResponseMessage(4, null, const(ResponseError)(serverNotInitialized, "Dub isn't initialized yet", null))
{"code":-32002,"data":null,"message":"Dub isn't initialized yet"}
2017-12-27T18:08:27.016:jsonrpc.d:send:66 {"error":{"code":-32002,"data":null,"message":"Dub isn't initialized yet"},"id":4,"jsonrpc":"2.0"}
Server: 2017-12-27T18:08:27.910:main.d:main:289 Request processed in 957.235 milliseconds
```

here you see the workspace structure:
![image](https://user-images.githubusercontent.com/776816/34388014-b8d9aa94-eb31-11e7-9d36-8c30e3909aa2.png)

here you see that indeed it tries to start in the wrong of the two contained folders:
`2017-12-27T18:08:21.364:extension.d:initialize:139 Initializing serve-d for /Users/stephan/code/liveask/frontend`

I doubt that it relates to #111 because if it would only try the `backend` folder first everything would be fine (i forced it by renaming^^)

**Comment by WebFreak001** [comment] 2017-12-27 17:35
```
2017-12-27T18:08:21.529:extension.d:safe:48 object.Exception@../../../../../.dub/packages/dub-1.4.1/dub/source/dub/dependency.d(657): Invalid SemVer format: ^2.4.1
```

I think it dislikes these kinds of ranges

**Comment by Extrawurst** [comment] 2017-12-27 21:15
Yes because it tries to swallow a freaking package.json in the frontend folder which - surprise - is valid in npm territory... Did you even read my post? 😉

**Comment by WebFreak001** [comment] 2019-01-05 01:52
should be fixed for a while... when #111 got fixed I also added a check if it's a package.json and in general it all seems to work with multiple workspaces now

**Closed by WebFreak001** 2019-01-05 01:52 UTC
