### ISSUE TITLE
The capacity property is not suggested

### ISSUE THREAD

**Issue by HuskyNator** [Pure-D/code-d#414] opened 2022-07-01 12:41 UTC
Although part of the specification (horribly noted at that https://forum.dlang.org/post/dceotfeduswpaoqodgww@forum.dlang.org), the `.capacity` property of arrays is not suggested by autocomplete.
Other properties correctly are (including those applicable to all expressions https://dlang.org/spec/property.html#alignof)

![image](https://user-images.githubusercontent.com/17416803/176896407-dac77de1-681e-4f17-8534-03047e0dc0db.png)

Also note this property is also valid for static arrays (although it yields 0)

**Comment by WebFreak001** [comment] 2022-07-01 12:45
capacity is not part of the specification, but part of the druntime: https://dlang.org/phobos/object.html#.capacity

this needs UFCS support, so closing as duplicate of #319

**Closed as completed by WebFreak001** 2022-07-01 12:45 UTC

**Comment by HuskyNator** [comment] 2022-07-01 12:55
I see, had no clue this was even part of phobos, my apologies.
