### ISSUE TITLE
Show type information on hover

### ISSUE THREAD

**Issue by theonenotzero** [Pure-D/code-d#402] opened 2022-04-12 09:30 UTC
Currently it's not possible to determine the type of a variable or the signature of a function without jumping to the definition.

#108 suggests to use ctrl+hover but that's a cheap workaround, and doesn't show the type if declared using `auto`. Other languages have this feature, including but not limited to TypeScript, C++ and even Python.

**Comment by WebFreak001** [comment] 2022-04-12 14:15
duplicate of #366 and https://github.com/Pure-D/serve-d/issues/140

**Closed by WebFreak001** 2022-04-12 14:15 UTC

**Comment by theonenotzero** [comment] 2022-04-14 10:09
This issue looks like it's been open for a long time, are there any plans to implement this feature soon?
