### ISSUE TITLE
`requests` lib is too old to run with OpenSSL 3.0

### ISSUE THREAD

**Issue by ledyba** [Pure-D/code-d#443] opened 2023-01-02 12:21 UTC
Hi, I'm using this plugin on Ubuntu 22.04 (x86_64):

However, output says:

```
[Info  - 8:23:03 PM] Connection to server got closed. Server will restart.
object.Exception@../../../.dub/packages/requests-1.1.7/requests/source/requests/ssl_adapter.d(193): loading openssl: unknown version for init
```

It looks `requests` package is too old:

https://github.com/ikod/dlang-requests/issues/148

**Comment by WebFreak001** [comment] 2023-01-02 13:27
are you on nightly or pre-release? the current stable is known-broken

To change to beta or nightly release, go into the VSCode user settings (Ctrl-,) and change the `d.servedReleaseChannel` setting to beta or nightly. Then reload VSCode (Ctrl-Shift-P -> Reload Window)

duplicate of https://github.com/Pure-D/serve-d/issues/280

**Closed by WebFreak001** 2023-01-02 13:27 UTC

**Comment by ledyba** [comment] 2023-01-02 13:51
It works, thanks!
