### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 564064202** [Pure-D/code-d#278] opened 2019-11-19 08:19 UTC
Dlang lacks a good IDE,and code-d is a good  IDE.
But I can't config it well in a week on linux(I can't debug and I don't how to config it).
I think everybody want to use Dlang will come across this problem,so 
I suggest you give us a detail help document.

**Comment by WebFreak001** [comment] 2019-11-19 08:20
duplicate of #240

**Closed by WebFreak001** 2019-11-19 08:20 UTC
