### ISSUE TITLE
DCD fails on macOS while working on fluent-asserts library

### ISSUE THREAD

**Issue by gedaiu** [Pure-D/code-d#342] opened 2021-01-06 08:28 UTC
It looks like on macOS DCD does not work properly. Is it possible to stop DCD? Also is annoying that after each error in DCD, the window switches to the DCD output. It would be nice if this would not happen so I can use the vs code terminal... 

DCD fails with the following error:

```
dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /Users/bogdan/.code-d/bin/dcd-client
  Expected in: /usr/lib/libSystem.B.dylib
2021-01-06T09:23:54.002 [error] extension.d:1090:__lambda1 Failed to attach DCD component to /Users/bogdan/gg/fluent-asserts: client & server version mismatch
{"code":-32603,"data":"object.Exception@..\/..\/..\/.dub\/packages\/workspace-d-3.6.0-pre.8\/workspace-d\/source\/workspaced\/backend.d(179): Attempted to get unknown instance component DCDComponent in instance cwd:\/Users\/bogdan\/gg\/fluent-asserts\n----------------\n??:? pure @safe void core.internal.utf.validate!(immutable(dchar)[]).validate(scope const(immutable(dchar)[])) [0x10599342e]\n??:? pure nothrow @safe int rt.cover.expandTabs(char[], int).__foreachbody3(ref ulong, ref dchar).__foreachbody3(ref char) [0x1059b1486]\n??:? int rt.dmain2.formatThrowable(object.Throwable, void delegate(scope const(char[])) nothrow).__foreachbody3(object.Throwable).__foreachbody2(object.Throwable) [0x1059b213e]\n??:? inout inout(workspaced.com.dcd.DCDComponent) workspaced.backend.WorkspaceD.Instance.get!(workspaced.com.dcd.DCDComponent).get() [0x10520dfff]\n??:? pure nothrow @nogc @safe void served.types.lspRouter.processRequestObservers!(served.lsp.protocol.CodeAction[]).processRequestObservers(served.lsp.protocol.RequestMessage, served.lsp.protocol.CodeAction[]) [0x10519acec]\n??:? served.lsp.protocol.CodeAction[] served.types.lspRouter.eventProcessor.emitProtocol!(served.utils.events.protocolMethod, served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5, true).emitProtocol(immutable(char)[], std.json.JSONValue).__lambda4!(immutable(char)[], served.lsp.protocol.CodeAction[] function(served.lsp.protocol.CodeActionParams)*, served.utils.events.protocolMethod).__lambda4(immutable(char)[], served.lsp.protocol.CodeAction[] function(served.lsp.protocol.CodeActionParams)*, served.utils.events.protocolMethod).callSymbol() [0x10519a370]\n??:? void served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5!(immutable(char)[], served.lsp.protocol.CodeAction[] delegate(), served.utils.events.protocolMethod).__lambda5(immutable(char)[], served.lsp.protocol.CodeAction[] delegate(), served.utils.events.protocolMethod) [0x10519a5e0]\n??:? bool served.types.lspRouter.eventProcessor.iterateExtensionMethodsByUDA!(served.utils.events.protocolMethod, served.types.lspRouter.eventProcessor.emitProtocol!(served.utils.events.protocolMethod, served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5, true).emitProtocol(immutable(char)[], std.json.JSONValue).__lambda4, true).iterateExtensionMethodsByUDA() [0x1051963ea]\n??:? pure nothrow @nogc @safe bool std.algorithm.searching.canFind!().canFind!(immutable(char)[][], immutable(char)[]).canFind(immutable(char)[][], scope immutable(char)[]) [0x105188c3f]\n??:? void served.types.lspRouter.gotRequest(served.lsp.protocol.RequestMessage).__lambda2() [0x10518ab56]\n??:? pure nothrow @nogc @trusted void core.thread.context.Callable.opAssign(void delegate()).__lambda2() [0x1059954e3]","message":"Attempted to get unknown instance component DCDComponent in instance cwd:\/Users\/bogdan\/gg\/fluent-asserts"}
[Error - 9:23:54 AM] Request textDocument/codeAction failed.
  Message: Attempted to get unknown instance component DCDComponent in instance cwd:/Users/bogdan/gg/fluent-asserts
  Code: -32603 
object.Exception@../../../.dub/packages/workspace-d-3.6.0-pre.8/workspace-d/source/workspaced/backend.d(179): Attempted to get unknown instance component DCDComponent in instance cwd:/Users/bogdan/gg/fluent-asserts
----------------
??:? pure @safe void core.internal.utf.validate!(immutable(dchar)[]).validate(scope const(immutable(dchar)[])) [0x10599342e]
??:? pure nothrow @safe int rt.cover.expandTabs(char[], int).__foreachbody3(ref ulong, ref dchar).__foreachbody3(ref char) [0x1059b1486]
??:? int rt.dmain2.formatThrowable(object.Throwable, void delegate(scope const(char[])) nothrow).__foreachbody3(object.Throwable).__foreachbody2(object.Throwable) [0x1059b213e]
??:? inout inout(workspaced.com.dcd.DCDComponent) workspaced.backend.WorkspaceD.Instance.get!(workspaced.com.dcd.DCDComponent).get() [0x10520dfff]
??:? pure nothrow @nogc @safe void served.types.lspRouter.processRequestObservers!(served.lsp.protocol.CodeAction[]).processRequestObservers(served.lsp.protocol.RequestMessage, served.lsp.protocol.CodeAction[]) [0x10519acec]
??:? served.lsp.protocol.CodeAction[] served.types.lspRouter.eventProcessor.emitProtocol!(served.utils.events.protocolMethod, served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5, true).emitProtocol(immutable(char)[], std.json.JSONValue).__lambda4!(immutable(char)[], served.lsp.protocol.CodeAction[] function(served.lsp.protocol.CodeActionParams)*, served.utils.events.protocolMethod).__lambda4(immutable(char)[], served.lsp.protocol.CodeAction[] function(served.lsp.protocol.CodeActionParams)*, served.utils.events.protocolMethod).callSymbol() [0x10519a370]
??:? void served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5!(immutable(char)[], served.lsp.protocol.CodeAction[] delegate(), served.utils.events.protocolMethod).__lambda5(immutable(char)[], served.lsp.protocol.CodeAction[] delegate(), served.utils.events.protocolMethod) [0x10519a5e0]
??:? bool served.types.lspRouter.eventProcessor.iterateExtensionMethodsByUDA!(served.utils.events.protocolMethod, served.types.lspRouter.eventProcessor.emitProtocol!(served.utils.events.protocolMethod, served.types.lspRouter.processRequest(served.lsp.protocol.RequestMessage).__lambda5, true).emitProtocol(immutable(char)[], std.json.JSONValue).__lambda4, true).iterateExtensionMethodsByUDA() [0x1051963ea]
??:? pure nothrow @nogc @safe bool std.algorithm.searching.canFind!().canFind!(immutable(char)[][], immutable(char)[]).canFind(immutable(char)[][], scope immutable(char)[]) [0x105188c3f]
??:? void served.types.lspRouter.gotRequest(served.lsp.protocol.RequestMessage).__lambda2() [0x10518ab56]
??:? pure nothrow @nogc @trusted void core.thread.context.Callable.opAssign(void delegate()).__lambda2() [0x1059954e3]
2021-01-06T09:23:54.113 [trace] dub.d:129:lint dub build finished in 1 sec, 519 ms, 709 μs, and 7 hnsecs with 0 issues
2021-01-06T09:23:54.113 [trace] dub.d:130:lint []
Running dub build
2021-01-06T09:23:54.113 [trace] async.d:79:setTimeout Setting timeout for 1 sec, 619 ms, 709 μs, and 7 hnsecs
2021-01-06T09:23:54.225 [trace] async.d:38:parallelMain Calling timeout
2021-01-06T09:23:55.533 [trace] dub.d:129:lint dub build finished in 1 sec, 420 ms, and 82 μs with 0 issues
2021-01-06T09:23:55.533 [trace] dub.d:130:lint []
2021-01-06T09:23:55.741 [trace] async.d:38:parallelMain Calling timeout
2021-01-06T09:24:01.597 [trace] serverbase.d:115:__lambda5 Calling provideCodeLens
2021-01-06T09:24:01.608 [trace] serverbase.d:115:__lambda5 Calling provideCodeLens
2021-01-06T09:24:13.894 [trace] serverbase.d:115:__lambda5 Calling provideCodeLens
2021-01-06T09:24:13.907 [trace] serverbase.d:115:__lambda5 Calling provideCodeLens
2021-01-06T09:24:22.584 [trace] serverbase.d:351:run GC run in 8 ms, 803 μs, and 4 hnsecs. Freed 1660448 bytes (28117344 bytes allocated, 45282976 bytes available)
2021-01-06T09:24:52.599 [trace] serverbase.d:351:run GC run in 7 ms, 174 μs, and 9 hnsecs. Freed 43536 bytes (28117568 bytes allocated, 45282752 bytes available)
```

**Comment by WebFreak001** [comment] 2022-01-20 20:26
seems like duplicate of #312 

Should be fixed on latest code-d/serve-d

**Closed by WebFreak001** 2022-01-20 20:26 UTC
